/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BoB8r2Zw6O3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:


To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import Link from "next/link"
import { Libre_Franklin } from 'next/font/google'
import { Rubik } from 'next/font/google'

const libreFranklin = Libre_Franklin({
  subsets: ['latin'],
  display: 'swap',
})

const rubik = Rubik({
  subsets: ['latin'],
  display: 'swap',
})

export function Landing() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gradient-to-br from-primary to-secondary">
      <div className="max-w-4xl w-full px-6 py-12 bg-background rounded-xl shadow-xl">
        <div className="space-y-6">
          <div className="text-center">
            <h1 className="text-4xl font-bold text-secondary-foreground dark:text-secondary-foreground">
              URL Shortener
            </h1>
            <p className="text-muted-foreground">Shorten your long URLs with ease.</p>
          </div>
          <form className="flex gap-4" >
            <Input
              type="url"
              placeholder="Enter your long URL"
              className="flex-1 bg-muted text-primary-foreground placeholder:text-muted-foreground"
            />
            <Button type="submit" className="bg-primary text-primary-foreground hover:bg-primary/90">
              Shorten
            </Button>
          </form>
          <div className={`${libreFranklin.className} space-y-4`}>
            <Card>
              <CardContent className="flex items-center justify-between">
                <div>
                  <Link href="#" className="text-primary hover:underline" prefetch={false} >
                    example.com/abc123
                  </Link>
                  <p>
                    <img
                      src="/placeholder.svg"
                      width="16"
                      height="16"
                      alt="Favicon"
                      className="mr-2 inline-block"
                      style={{ aspectRatio: "16/16", objectFit: "cover" }}
                    />
                    https://www.example.com/very-long-url-that-needs-to-be-shortened
                  </p>
                </div>
                <p className="text-muted-foreground">2023-08-02 12:34 PM</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="flex items-center justify-between">
                <div>
                  <Link href="#" className="text-primary hover:underline" prefetch={false}>
                    example.com/def456
                  </Link>
                  <p className="text-muted-foreground">https://www.example.com/another-long-url-to-shorten</p>
                </div>
                <p className="text-muted-foreground">2023-08-01 09:15 AM</p>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="flex items-center justify-between">
                <div>
                  <Link href="#" className="text-primary hover:underline" prefetch={false}>
                    example.com/ghi789
                  </Link>
                  <p className="text-muted-foreground">https://www.example.com/this-url-is-also-very-long</p>
                </div>
                <p className="text-muted-foreground">2023-07-30 03:42 PM</p>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  )
}
